### PR TITLE
Remove unsafe usage of Rf_eval (close #498)

### LINKED ISSUE #498: eliminate unsafe usages of 'Rf_eval'
There are a number of places in Rcpp where we use `Rf_eval` rather than the more appropriate / safer `Rcpp_eval`:

```
$ ag -Q "Rf_eval"
inst/include/Rcpp/api/meat/Rcpp_eval.h
57:    Shield<SEXP> res(::Rf_eval(call, R_GlobalEnv));
69:            Shield<SEXP> conditionMessage(::Rf_eval(conditionMessageCall, R_GlobalEnv));

inst/include/Rcpp/Environment.h
114:                res = Rf_eval( res, env ) ;
135:                res = Rf_eval( res, env ) ;
206:                    Rf_eval( call, R_GlobalEnv ) ;

inst/include/Rcpp/exceptions.h
132:    Rcpp::Shield<SEXP> calls( Rf_eval( sys_calls_expr, R_GlobalEnv ) );
197:    Rcpp::Shield<SEXP> simpleError( Rf_eval(simpleErrorExpr, R_GlobalEnv) );
326:    Rf_eval( expr, R_GlobalEnv ) ;

inst/include/Rcpp/Language.h
148:            return Rf_eval( Storage::get__(), R_GlobalEnv) ;
151:            return Rf_eval( Storage::get__(), env) ;

inst/include/Rcpp/macros/macros.h
55:       Rf_eval( expr, R_GlobalEnv ) ;                                                            \

inst/include/Rcpp/Module.h
457:    Rf_eval(__load_module_call__), R_GlobalEnv );

inst/include/Rcpp/proxy/FieldProxy.h
45:            return Rf_eval( call, R_GlobalEnv ) ;
50:            parent.set__( Rf_eval( call, R_GlobalEnv ) );
70:            return Rf_eval( call, R_GlobalEnv ) ;

inst/include/Rcpp/r_cast.h
98:                    Shield<SEXP> res( Rf_eval( call, R_GlobalEnv ) ) ;

inst/unitTests/cpp/language.cpp
71:    return Rf_eval( call, R_GlobalEnv ) ;

src/barrier.cpp
98:        Rcpp::Shield<SEXP> RCPP(Rf_eval(call, R_GlobalEnv));
140:    Rcpp::Shield<SEXP> RCPP(Rf_eval(call, R_GlobalEnv));
```

Most of these (barring ones used directly for R error / exception handling) should likely be `Rcpp_eval`.

### PR DESCRIPTION
**Pull request by thirdwing**
@kevinushey

### CODE REVIEW

File: inst/include/Rcpp/api/meat/Rcpp_eval.h [hunk 1]
```diff
@@ -54,7 +54,7 @@ inline SEXP Rcpp_eval(SEXP expr, SEXP env) {
     SET_TAG(CDDR(CDR(call)), ::Rf_install("interrupt"));
 
     // execute the call
-    Shield<SEXP> res(::Rf_eval(call, R_GlobalEnv));
+    Shield<SEXP> res(::Rf_eval(call, env));
```
Comment (coatless) [inline inst/include/Rcpp/api/meat/Rcpp_eval.h]: Why the switch from `R_GlobalEnv` to `env` here but not on [line 69](https://github.com/thirdwing/Rcpp/blob/20d02de09b155b10cb463b7a3adea35dd8267fab/inst/include/Rcpp/api/meat/Rcpp_eval.h)? 

```cpp
Shield<SEXP> conditionMessage(::Rf_eval(conditionMessageCall, R_GlobalEnv));
```

Comment (thirdwing) [inline inst/include/Rcpp/api/meat/Rcpp_eval.h]: Actually this switch is not necessary, since we already have the `env` from `evalq`. I involve this when trying to simplify `Rcpp_eval`. I will update.

**Comment by eddelbuettel** [comment]
Thank you -- nice work.  Is that "all of them" or just the ones you thought we could safely change?  I seem to recall @kevinushey mentioning that maybe some needed to remain or something to that extend.  Or am I misremembering?   Anybody to second the thumbs-up?

**Comment by kevinushey** [comment]
Looks great, thanks! @eddelbuettel I was thinking that the `Rf_eval`s e.g. here:

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/exceptions.h#L197
https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/exceptions.h#L326

probably don't want to be touched, as that's code that will get called in our try-catch macros, e.g. at

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/macros/macros.h#L37-L57

and so `Rcpp_eval`s within there would be executed outside the 'safety' of a try-catch block, IIUC.

File: inst/include/Rcpp/api/meat/Rcpp_eval.h (hunk 1 above)
Comment (kevinushey) [inline inst/include/Rcpp/api/meat/Rcpp_eval.h]: The `evalq` call itself might be unneeded, really -- we could probably omit constructing of the `evalq` bit and just evaluate the `tryCatch` expression in `env`.

We want to ensure that `expr` is evaluated in `env`, but the other usages likely want to just be evaluated in the global environment.

**Comment by eddelbuettel** [comment]
Thank you both -- in it goes!  And I resolve to do a full rev.dep check tomorrow. Worst case we revert.

**Comment by eddelbuettel** [comment]
Just for the record it passed the rev.dep with flying colours as expected.
