### PR TITLE
Remove cast to R_xlen_t (closes #1334)

### LINKED ISSUE #1334: Bugs with Rcpp==1.0.13
Problem: update matrix passed by reference from R

Code:

```R
 Rcpp::cppFunction("
 void test_arma(arma::mat& A) {
 A.fill(1);
 return;
 }", depends = "RcppArmadillo")

 Rcpp::cppFunction("
 void test_eigen(Eigen::Map<Eigen::MatrixXd> A) {
 A.fill(1);
 return;
 }", depends = "RcppEigen")

 Rcpp::cppFunction("
 void test_rcpp(Rcpp::NumericMatrix A) {
 A.fill(1);
 return;
 }")


 f <- function(M = 1e6, N = 1e4, init = "array", test = "arma") {
   if (init == "array") {
     A <- array(0, c(M, N))
   } else {
     A <- matrix(0, nrow = M, ncol = N)
   }
   label <- paste0("start, ", init, ", ", test)
   before <- paste0("A[1, 1] = ", A[1, 1], ", A[M, N] = ", A[M, N])
   x <- A[M, N]
   if (test == "arma") {
     test_arma(A)
   } else if (test == "rcpp") {
     test_rcpp(A)
   } else if (test == "eigen") {
     test_eigen(A)
   }
   after <- paste0("A[1, 1] = ", A[1, 1], ", A[M, N] = ", A[M, N])
   y <- A[M, N]
   worked <- c("worked", "not worked")[1 + as.integer(x == y)]
   message(paste0(label, " before ", before, " after ", after, " ", worked))
 }

 for (init in c("array", "matrix")) {
   for (test in c("arma", "rcpp", "eigen")) {
     system.time(f(M = 1e6, N = 1e4, init = init, test = test))
     gc()
   }
 }
```

Results and Sessioninfo:

image

Reproducible conda env:
```shell
mamba create -n r44 r-base=4.4.0 r-rcpp=1.0.13 r-rcpparmadillo r-rcppeigen
```

Btw, with Rcpp=1.0.12, the above code reported: 

```
start, array, arma before A[1, 1] = 0, A[M, N] = 0 after A[1, 1] = 1, A[M, N] = 0 not worked
start, array, rcpp before A[1, 1] = 0, A[M, N] = 0 after A[1, 1] = 1, A[M, N] = 1 worked
start, array, eigen before A[1, 1] = 0, A[M, N] = 0 after A[1, 1] = 1, A[M, N] = 1 worked
start, matrix, arma before A[1, 1] = 0, A[M, N] = 0 after A[1, 1] = 1, A[M, N] = 0 not worked
start, matrix, rcpp before A[1, 1] = 0, A[M, N] = 0 after A[1, 1] = 1, A[M, N] = 1 worked
start, matrix, eigen before A[1, 1] = 0, A[M, N] = 0 after A[1, 1] = 1, A[M, N] = 1 worked
> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Copenhagen
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.0           RcppEigen_0.3.4.0.0      tools_4.4.0              RcppArmadillo_0.12.8.4.0 Rcpp_1.0.12             
```

### PR DESCRIPTION
**Pull request by eddelbuettel**
This addresses the issue highlighted in #1334 by @zilong-li.  Thanks again for noticing I closed this prematurely---my bad!

A rev.dep. has been started on that old machine so it will be a while until it is done.  So far no issues but many, many more packages to go.

#### Checklist

- [x] Code compiles correctly
- [x] `R CMD check` still passes all tests
- [ ] Preferably, new tests were added which fail without the change
- [x] Document the changes by file in [ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog)

### CODE REVIEW

File: inst/include/Rcpp/vector/Vector.h [hunk 1]
```diff
@@ -331,7 +331,7 @@ class Vector :
     }
 
     inline iterator begin() { return cache.get() ; }
-    inline iterator end() { return cache.get() + static_cast<int>(size()) ; }
+    inline iterator end() { return cache.get() + static_cast<R_xlen_t>(size()) ; }
     inline const_iterator begin() const{ return cache.get_const() ; }
     inline const_iterator end() const{ return cache.get_const() + size() ; }
```
Comment (eddelbuettel) [inline inst/include/Rcpp/vector/Vector.h:336]: A related question is whether the two const interators on lines 336 and 338 should also get the cast.

Comment (Enchufa2) [reply inst/include/Rcpp/vector/Vector.h:336]: It feels certainly wrong that there is a cast only there. What image did you use to reproduce the warnings?

Comment (Enchufa2) [reply inst/include/Rcpp/vector/Vector.h:336]: Also, given that this was address in two steps ([one](be2517ab67c6152cf3da4bbd86dc237aa5240aa1), [two](https://github.com/RcppCore/Rcpp/commit/520797316ac797b28a24e91ca3c34eaed72605f7)), and this line was part of the first PR, is it possible that, after the second set of changes, the `static_cast` is not needed anymore? Because `size()` already returns `R_xlen_t`. (Specifically, after [this change](https://github.com/RcppCore/Rcpp/commit/520797316ac797b28a24e91ca3c34eaed72605f7#diff-34caef0e91184bc37a7e55f4d5c173658994f48447c4dc20d91fd963b6557a71R32)).

We should be fine just dropping the cast.

Comment (eddelbuettel) [reply inst/include/Rcpp/vector/Vector.h:336]: No issues with `clang++-19` with the compiler flags that tickled this, either in installation or check.  Here is installation (in a `rocker/r-base` container using Debian testing/unstable)

```sh
root@e47796620ac8:/work# install.r
* installing *source* package found in current working directory ...
* installing *source* package ‘Rcpp’ ...
** using staged installation
** libs
using C++ compiler: ‘Debian clang version 19.1.0 (4)’
clang++-19  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/      -fpic  -Wall -O3 -pedantic -Wconversion -Wno-sign-conversion   -c api.cpp -o api.o
clang++-19  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/      -fpic  -Wall -O3 -pedantic -Wconversion -Wno-sign-conversion   -c attributes.cpp -o attributes.o
clang++-19  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/      -fpic  -Wall -O3 -pedantic -Wconversion -Wno-sign-conversion   -c barrier.cpp -o barrier.o
clang++-19  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/      -fpic  -Wall -O3 -pedantic -Wconversion -Wno-sign-conversion   -c date.cpp -o date.o
clang++-19  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/      -fpic  -Wall -O3 -pedantic -Wconversion -Wno-sign-conversion   -c module.cpp -o module.o
clang++-19  -I"/usr/share/R/include" -DNDEBUG -I../inst/include/      -fpic  -Wall -O3 -pedantic -Wconversion -Wno-sign-conversion   -c rcpp_init.cpp -o rcpp_init.o
clang++-19 -Wl,-S -shared -L/usr/lib/R/lib -Wl,-z,relro -o Rcpp.so api.o attributes.o barrier.o date.o module.o rcpp_init.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-work/00new/Rcpp/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Rcpp)
root@e47796620ac8:/work# 
```

Comment (eddelbuettel) [reply inst/include/Rcpp/vector/Vector.h:336]: (To clarify, that was after I removed the cast.)

Comment (eddelbuettel) [reply inst/include/Rcpp/vector/Vector.h:336]: I've now pushed it.  I will take the slow read here and let the current (2 1/2 day total !!) rev.dep test finish, fill-in missing build dependencies it uncovers and then re-run again with the cast removed.

**Review by Enchufa2 — APPROVED** [review]
Thumbs up here conditional to a clean revdep. :)

**Comment by eddelbuettel** [comment]
No issues found in reverse dependency checking so in it goes!
