### PR TITLE
Fixes exception call stack for C++ exceptions

### LINKED ISSUE #579: C++ exceptions are not generating proper condition objects
In particular the `call` and `cppstack` elements are not being populated appropriately. Looks like this condition object is created from [exception_to_r_condition](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/inst/include/Rcpp/exceptions.h#L173-L183). The same behavior exists on MacOS (clang) and Windows. I did not test Linux.

### Steps to reproduce
```r
download.file("https://github.com/RcppCore/rcpp-gallery/raw/gh-pages/src/2013-01-13-intro-to-exceptions.cpp", "2013-01-13-intro-to-exceptions.cpp")
Rcpp::sourceCpp("2013-01-13-intro-to-exceptions.cpp", embeddedR = FALSE)
str(tryCatch(takeLog(-1.0), error = function(e) e))
#> List of 3
#>  $ message : chr "Inadmissible value"
#>  $ call    : language eval(substitute(expr), envir, enclos)
#>  $ cppstack: NULL
#>  - attr(*, "class")= chr [1:4] "std::range_error" "C++Error" "error" "condition"
```

<details>
<summary>Session Info</summary>

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] tools_3.3.0 Rcpp_0.12.7
```

</details>

### PR DESCRIPTION
**Pull request by jimhester**
Also adds support for populating the cppstack for Rcpp::exceptions when
using clang and a str method to make printing a little nicer.

``` r
library(Rcpp)
cppFunction('double takeLog(double val) {
    if (val <= 0.0) {
      throw std::range_error("Inadmissible value");
    }
    return log(val);
  }')

# Regular exceptions now work as before
takeLog(-1)
#> Error in takeLog(-1): Inadmissible value
tryCatch(takeLog(-1), error = identity)
#> <std::range_error in takeLog(-1): Inadmissible value>
str(tryCatch(takeLog(-1), error = identity))
#> List of 3
#>  $ message : chr "Inadmissible value"
#>  $ call    : language takeLog(-1)
#>  $ cppstack: NULL
#>  - attr(*, "class")= chr [1:4] "std::range_error" "C++Error" "error" "condition"

# Rcpp exceptions now work with clang as well, and the
# str method prints the full cpp stacktrace
cppFunction('double takeLog(double val) {
    if (val <= 0.0) {
      throw Rcpp::exception("Inadmissible value");
    }
    return log(val);
  }')
str(tryCatch(takeLog(-1), error = identity))
#> List of 3
#>  $ message : chr "Inadmissible value"
#>  $ call    : language takeLog(-1)
#>  $ cppstack:
#>  stack_trace(char const*, int)
#>    Rcpp::exception::exception(char const*)
#>    Rcpp::exception::exception(char const*)
#>    takeLog(double)
#>    sourceCpp_7_takeLog
#>    do_dotcall
#>    Rf_eval
#>    Rf_applyClosure
#>    Rf_eval
# ... manually removed for brevity
#>  - attr(*, "class")= chr [1:4] "Rcpp::exception" "C++Error" "error" "condition"
```

Fixes #579

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks very promising.  I had been pondering releasing this weekend but may as well push back a week.

File: R/exceptions.R [hunk 1]
```diff
@@ -33,4 +33,6 @@
     warnings
 }
 
-
+`str.Rcpp_stack_trace` <- function(x, ...) {
```
Comment (eddelbuettel) [inline R/exceptions.R]: Not a fan of the ` style for functions, personally.  Add little here but oh well -- we have a mixed bag of styles in the code already.

Comment (eddelbuettel) [inline R/exceptions.R]: Almost not worth a commit; we can clean up another time.  We still have inconsistent white-space and whatnot.

Oh, and there he did :)   Thanks.

File: inst/include/Rcpp/exceptions.h [hunk 2]
```diff
@@ -127,17 +127,17 @@ namespace Rcpp{
 } // namespace Rcpp
 
 inline SEXP get_last_call(){
-    SEXP sys_calls_symbol = Rf_install( "sys.calls" ) ;
-    Rcpp::Shield<SEXP> sys_calls_expr( Rf_lang1(sys_calls_symbol) );
+    SEXP sys_calls_symbol = Rf_install( "sys.call" ) ;
+
+    // -9 Skips the wrapped tryCatch from Rcpp_eval
+    Rcpp::Shield<SEXP> sys_calls_expr( Rf_lang2(sys_calls_symbol, Rf_ScalarInteger(-9)) );
```
Comment (kevinushey) [inline inst/include/Rcpp/exceptions.h]: I wonder if we can do something a bit more robust here? (Does this work in the presence of eager byte-compilation?)

Comment (eddelbuettel) [inline inst/include/Rcpp/exceptions.h]: Any thoughts on how?

Comment (jjallaire) [inline inst/include/Rcpp/exceptions.h]: At the last R Summit Luke warned against hard coding the number of calls on the stack so I think this might indeed fail in the presence of said eager byte-compilation.

Comment (jimhester) [inline inst/include/Rcpp/exceptions.h]: Yes the other way to do it would be to go back to using `sys.calls()` and return the call just prior to `tryCatch(sys.calls(), error = identity, interrupt = identity)`, which is what we call from the Rcpp_eval at https://github.com/RcppCore/Rcpp/pull/582/files#diff-5b6f3a71a6058dccfe3c3426c64110d2L132.

For example making a small change [1] to this PR, running the `tryCatch(takeLog-1), error = identity)` example from above, setting a breakpoint at exception.h:135 and running `Rf_PrintValue(calls)` gets you this callstack [2].

Writing the code to properly and robustly match `[[6]]` below is not something I have quite worked out how to do yet, which is why I went for the simpler solution to this PR initially, suggestions welcome.

[1]
```diff
diff --git a/inst/include/Rcpp/exceptions.h b/inst/include/Rcpp/exceptions.h
index b35d4bb..cd8e46f 100644
--- a/inst/include/Rcpp/exceptions.h
+++ b/inst/include/Rcpp/exceptions.h
@@ -127,10 +127,10 @@ namespace Rcpp{
 } // namespace Rcpp

 inline SEXP get_last_call(){
-    SEXP sys_calls_symbol = Rf_install( "sys.call" ) ;
+    SEXP sys_calls_symbol = Rf_install( "sys.calls" ) ;

     // -9 Skips the wrapped tryCatch from Rcpp_eval
-    Rcpp::Shield<SEXP> sys_calls_expr( Rf_lang2(sys_calls_symbol, Rf_ScalarInteger(-9)) );
+    Rcpp::Shield<SEXP> sys_calls_expr( Rf_lang1(sys_calls_symbol) );
     Rcpp::Shield<SEXP> calls( Rcpp_eval( sys_calls_expr, R_GlobalEnv ) );
     return calls;
 }
```

[2]
```r
[[1]]
tryCatch(takeLog(-1), error = identity)

[[2]]
tryCatchList(expr, classes, parentenv, handlers)

[[3]]
tryCatchOne(expr, names, parentenv, handlers[[1L]])

[[4]]
doTryCatch(return(expr), name, parentenv, handler)

[[5]]
takeLog(-1)

[[6]]
tryCatch(evalq(sys.calls(), <environment>), error = function (x)
x, interrupt = function (x)
x)

[[7]]
tryCatchList(expr, classes, parentenv, handlers)

[[8]]
tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),
    names[nh], parentenv, handlers[[nh]])

[[9]]
doTryCatch(return(expr), name, parentenv, handler)

[[10]]
tryCatchList(expr, names[-nh], parentenv, handlers[-nh])

[[11]]
tryCatchOne(expr, names, parentenv, handlers[[1L]])

[[12]]
doTryCatch(return(expr), name, parentenv, handler)

[[13]]
evalq(sys.calls(), <environment>)

[[14]]
eval(substitute(expr), envir, enclos)
```

Comment (jimhester) [inline inst/include/Rcpp/exceptions.h]: https://github.com/RcppCore/Rcpp/pull/582/commits/bb82bd94e34caab8a5390514ba38f2aae1e194c6 now matches the expression exactly rather than relying on the position in the call stack

Comment (lionel-) [inline inst/include/Rcpp/exceptions.h]: The tricky part of looking at `sys.calls()` and related functions is to ignore intervening frames. `rlang:::trail_make()` is one way of getting the vector of relevant parent frames.

I think if you run `rlang::call_stack()` instead of `sys.calls()` here, you should get only a handful of frames instead of 14.

**Comment by jjallaire** [comment]
We can't take a dependency on rlang (we don't depend on any packages since 2/3 of CRAN recursively depends on us) so if we wanted to use that approach we'd need to copy the implementation into Rcpp (but it sounds like we may already have a solution that works well enough?)

**Comment by jimhester** [comment]
@jjallaire Yes there's definitely no need for an additional dependency here.

**Comment by lionel-** [comment]
yup I was only suggesting to copy `trail_make()`'s logic in case it made the task easier.

File: inst/include/Rcpp/exceptions.h [hunk 3]
```diff
@@ -126,18 +126,47 @@ namespace Rcpp{
...
+
+    SEXP cur, prev;
+    prev = cur = calls;
+    while(CDR(cur) != R_NilValue) {
+      SEXP expr = CAR(cur);
+
+      // We want the call just prior to the call from Rcpp_eval
+      // This conditional matches
+      // tryCatch(evalq(sys.calls(), .GlobalEnv), error = identity, interrupt = identity)
+      if (TYPEOF(expr) == LANGSXP &&
```
Comment (kevinushey) [inline inst/include/Rcpp/exceptions.h]: Can we refactor this into a separate function (e.g. in the `internal` namespace just above here)? E.g. `internal::is_Rcpp_eval_call` or something like that.

File: inst/include/Rcpp/exceptions.h [hunk 4]
```diff
@@ -126,18 +126,47 @@ namespace Rcpp{
...
+          Rf_length(expr) == 4 &&
+          nth(expr, 0) == tryCatch_symbol &&
+          CAR(nth(expr, 1)) == evalq_symbol &&
+          CAR(nth(nth(expr, 1), 1)) == sys_calls_symbol &&
```
Comment (kevinushey) [inline inst/include/Rcpp/exceptions.h]: Do we need to validate that the `evalq` call has a size of 3 here?

**Comment by kevinushey** [comment]
LGTM barring some nitpicks -- it's probably an issue we'll never encounter in practice but it seems like the current iteration of the code could fail if it found a stack frame like

```
tryCatch(evalq(1 + 1))
```

Ie, a somewhat more 'bare' `evalq` call inside of a `tryCatch` block.

**Comment by jimhester** [comment]
This is robust to the list size throughout, `nth()` checks the list length and returns a `R_NilValue` if the requested item is larger than the length. `CAR(R_NilValue) == R_NilValue` and `CDR(R_NilValue) == R_NilValue`, so all of the conditions will just return false in that case.

The function actually works perfectly fine if you remove the first two conditions entirely.
```r
TYPEOF(expr) == LANGSXP &&
          Rf_length(expr) == 4
```
I had them in there more for explicitness than anything else.

File: inst/include/Rcpp/exceptions.h (hunk 3 above)
Comment (jimhester) [inline inst/include/Rcpp/exceptions.h]: Done in https://github.com/RcppCore/Rcpp/pull/582/commits/9412f1f3d2ca36637709fa59d9fc816b2421de73

File: inst/include/Rcpp/exceptions.h (hunk 4 above)
Comment (jimhester) [inline inst/include/Rcpp/exceptions.h]: We don't _need_ to, see https://github.com/RcppCore/Rcpp/pull/582#issuecomment-260414949, but we can do so if you think it is better to be explicit about it.

Comment (kevinushey) [inline inst/include/Rcpp/exceptions.h]: Ah, I wasn't aware that `nth` validated the length already; thanks!

**Comment by kevinushey** [comment]
I wasn't aware that `nth()` did a length check already -- thanks for pointing that out! LGTM.

**Comment by jimhester** [comment]
Also I am happy to add some tests for this functionality to prevent future regressions, is there an existing test file that would be appropriate to put them in or should I make new ones?

**Comment by eddelbuettel** [comment]
> is there an existing test file that would be appropriate to put them in or should I make new ones?

Not sure. It is a little all over the place in `inst/unitTests/` and `inst/unitTests/cpp`.  Just apply some good judgment as usual.   A new file (or pair) for exceptions may be cleanest.

**Comment by eddelbuettel** [comment]
Apparently we already had `is_Rcpp_eval_call()` somewhere else:
https://travis-ci.org/RcppCore/Rcpp/builds/175788590

@jimhester Can you take another look?

**Comment by eddelbuettel** [comment]
Silly me.  Standard case of multiple compilation units sharing code from a header. I guess making the function `inline` would do it?

File: inst/include/Rcpp/exceptions.h [hunk 5]
```diff
@@ -126,40 +126,49 @@ namespace Rcpp{
...
+namespace internal {
+
+    inline SEXP nth(SEXP s, int n) {
+        return Rf_length(s) > n ? (n == 0 ? CAR(s) : CAR(Rf_nthcdr(s, n))) : R_NilValue;
+    }
+
+    // We want the call just prior to the call from Rcpp_eval
+    // This conditional matches
+    // tryCatch(evalq(sys.calls(), .GlobalEnv), error = identity, interrupt = identity)
+    bool is_Rcpp_eval_call(SEXP expr) {
```
Comment (eddelbuettel) [inline inst/include/Rcpp/exceptions.h]: Please try `inline bool`

**Comment by jimhester** [comment]
@eddelbuettel Yep, just did so in 65e502d, will write some tests in a few.

File: inst/include/Rcpp/exceptions.h [hunk 6]
```diff
@@ -126,40 +126,49 @@ namespace Rcpp{
 
 } // namespace Rcpp
 
-inline SEXP nth(SEXP s, int n) {
-  return Rf_length(s) > n ? (n == 0 ? CAR(s) : CAR(Rf_nthcdr(s, n))) : R_NilValue;
+namespace internal {
```
Comment (eddelbuettel) [inline inst/include/Rcpp/exceptions.h]: Looks like this accidentally was left outside of the outer  `namespace Rcpp` bombing compilation:

https://travis-ci.org/RcppCore/Rcpp#L2618

```
na.cpp:27:12: error: reference to ‘internal’ is ambiguous
     return internal::Rcpp_IsNA(x);
            ^
In file included from /home/travis/build/RcppCore/Rcpp/Rcpp.Rcheck/Rcpp/include/RcppCommon.h:122:0,
                 from /home/travis/build/RcppCore/Rcpp/Rcpp.Rcheck/Rcpp/include/Rcpp.h:27,
                 from na.cpp:22:
/home/travis/build/RcppCore/Rcpp/Rcpp.Rcheck/Rcpp/include/Rcpp/exceptions.h:129:20: note: candidates are: namespace internal { }
 namespace internal {
                    ^
In file included from /home/travis/build/RcppCore/Rcpp/Rcpp.Rcheck/Rcpp/include/Rcpp.h:27:0,
                 from na.cpp:22:
/home/travis/build/RcppCore/Rcpp/Rcpp.Rcheck/Rcpp/include/RcppCommon.h:45:24: note:                 namespace Rcpp::internal { }
     namespace internal {
                        ^
```

**Comment by jimhester** [comment]
Ok now have some simple tests for this as well.

**Comment by eddelbuettel** [comment]
This appears ready. I ran full reverse-depends checks overnight, have ran another set yesterday against master.

No new issues.  I plan to merge later today.
