### PR TITLE
Readonly file io error

### LINKED ISSUE #1345: File io error for sourceCpp of a readonly file
## Motivation

I am attempting to create a [Nix](https://nixos.org/) package for an R application which uses `Rcpp`.

The nature of Nix is that all installed files are readonly in the Nix store.

Attempting to `sourceCpp` such an installed C++ file results in a `file io error`.

This is a showstopper for Nix packaging of anything using Rcpp I think.  I can understand no good reason for not supporting readonly C++ sources.

## Evidence

Working example with writable C++ source:
```
it23677> Rscript hello-rcpp-world.R
Loading required package: Rcpp
/nix/store/106z10g87sccpaw7n8pnwlalhpxnc85q-R-4.3.3/lib/R/bin/R CMD SHLIB -o 'sourceCpp_2.so' 'hello-cpp-world.cpp'
using C++ compiler: ‘g++ (GCC) 13.2.0’
/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0/bin/c++ -std=gnu++17 -I"/nix/store/106z10g87sccpaw7n8pnwlalhpxnc85q-R-4.3.3/lib/R/include" -DNDEBUG   -I"/nix/store/yh83cz7v3vjw6r7nk05d55mkj77m3g3f-r-Rcpp-1.0.12/library/Rcpp/include" -I"/home/guestsi/vc/agr-github/RCpp-readonly-file-io-error"     -fpic  -g -O2  -c hello-cpp-world.cpp -o hello-cpp-world.o
/nix/store/i53w7x986ifmgzvb8da6zkfms4xzmdrk-gcc-wrapper-13.2.0/bin/c++ -std=gnu++17 -shared -L/nix/store/106z10g87sccpaw7n8pnwlalhpxnc85q-R-4.3.3/lib/R/lib -o sourceCpp_2.so hello-cpp-world.o -L/nix/store/106z10g87sccpaw7n8pnwlalhpxnc85q-R-4.3.3/lib/R/lib -lR
Hello CPP World
```

Making it readonly breaks things:
```
it23677> chmod 444 hello-cpp-world.cpp
it23677> Rscript hello-rcpp-world.R
Loading required package: Rcpp
Error: file io error: '/tmp/RtmpCCsssI/sourceCpp-x86_64-pc-linux-gnu-1.0.12/sourcecpp_277bc8f7c72b/hello-cpp-world.cpp'
Execution halted
Exception: Rscript exited with 1
  [tty 10]:1:1-27: Rscript hello-rcpp-world.R
```

`hello-rcpp-world.R` source:
```
require(Rcpp)

sourceCpp(file = "hello-cpp-world.cpp", showOutput = TRUE)

hello_cpp_world()
```

`hello-cpp-world.cpp` source:
```
#include <iostream>
using namespace std;

// [[Rcpp::export]]
void hello_cpp_world() {
  cout << "Hello CPP World" << endl;
}
```

## Version and Platform
I am using Rcpp 1.0.12 with R 4.3.3 on NixOS 24.11.  (NixOS is a Linux distro built with Nix.)

### PR DESCRIPTION
**Pull request by tesujimath**
Fixes #1345

```it23677> ls -l hello-cpp-world.cpp
-r--r--r-- 1 guestsi users 126 Nov 25 14:53 hello-cpp-world.cpp
it23677> Rscript hello-rcpp-world.R
Loading required package: Rcpp
Hello CPP World
```
#### Checklist

- [X] Code compiles correctly
- [ ] `R CMD check` still passes all tests
- [ ] Preferably, new tests were added which fail without the change
- [X] Document the changes by file in [ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog)

### CODE REVIEW

File: ChangeLog [hunk 1]
```diff
@@ -1,3 +1,6 @@
+2024-11-25  Simon Guest <simon.guest@tesujimath.org>
```
Comment (eddelbuettel) [inline ChangeLog:1]: Can you make it two spaces also between your name and your email?

Then one new line, and a tab (or eight spaces) to the *.

Thank you!

File: src/attributes.cpp [hunk 2]
```diff
@@ -3279,7 +3279,7 @@ namespace {
 
             // copy the source file to the build dir
             Rcpp::Function filecopy = Rcpp::Environment::base_env()["file.copy"];
-            filecopy(cppSourcePath_, generatedCppSourcePath(), true);
+            filecopy(cppSourcePath_, generatedCppSourcePath(), true, Rcpp::_["copy.mode"] = false);
```
Comment (eddelbuettel) [inline src/attributes.cpp:3282]: Nice. I'll look some more at that tomorrow over morning coffee -- this ensures we get 0644 irrespective of original permissionss?

**Review by eddelbuettel — COMMENTED** [review]
Two quick comments, one small request for change -- looks good generally.

File: src/attributes.cpp (hunk 2 above)
Comment (eddelbuettel) [reply src/attributes.cpp:3282]: Have by now caught up onto `help(file.copy)` -- this is perfect. Had worried that this code, because it dates back to before we had filesystem semantics from C++17 and all that, would have to do dance to do this portably.  But farming out to a call to then underlying R instance we always have is golden, and that function has that option.  Very nice.

File: ChangeLog (hunk 1 above)
Comment (tesujimath) [reply ChangeLog]: Done!

File: src/attributes.cpp (hunk 2 above)
Comment (eddelbuettel) [reply src/attributes.cpp:3282]: I generally have a mild dislike of  `Rcpp::_[...]` over the preferred `Rcpp::Named("...")` but they are equivalent, and the former is used in the file already.  So may change that another time....

**Review by eddelbuettel — APPROVED** [review]
Looks good, one micro nag notwithstanding, and addresses the issue.

Thanks for putting it up.
