### PR TITLE
Resolve #213: Cannot sapply lambda functions

### LINKED ISSUE #213: Cannot sapply lambda functions
With the cpp11 plugin on, Rcpp cannot sapply lambda functions. 

```cpp
#include <Rcpp.h>
using namespace Rcpp ;

// [[Rcpp:::plugins(cpp11)]]

// [[Rcpp::export]]
NumericVector double_up( NumericVector x ){
  return sapply( x, [](double x){ return x*x; } )
}

/*** R
  double_up( c(1,2) )
**/
```

I get : 

```
$ RcppScript /tmp/double.cpp
In file included from double.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/RcppCommon.h:159:
In file included from /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/traits/traits.h:74:
/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/traits/result_of.h:31:22: error: no type named 'result_type' in
      '<lambda at double.cpp:8:21>'
        typedef typename T::result_type type ;
                ~~~~~~~~~~~~^~~~~~~~~~~
/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/sugar/functions/sapply.h:105:34: note: in instantiation of template class
      'Rcpp::traits::result_of<<lambda at double.cpp:8:21> >' requested here
        typename ::Rcpp::traits::result_of<Function>::type ,
                                 ^
double.cpp:8:10: note: while substituting deduced template arguments into function template 'sapply' [with RTYPE = 14, NA = true, T = Rcpp::Vector<14, PreserveStorage>,
      Function = <lambda at double.cpp:8:21>]
  return sapply( x, [](double x){ return x*x; } )
         ^
double.cpp:8:10: error: no matching function for call to 'sapply'
  return sapply( x, [](double x){ return x*x; } )
         ^~~~~~
/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/vector/ListOf.h:134:3: note: candidate template ignored: could not match 'ListOf' against
      'Vector'
T sapply(const ListOf<T>& t, Function fun) {
  ^
/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/sugar/functions/sapply.h:109:1: note: candidate template ignored: substitution failure
      [with RTYPE = 14, NA = true, T = Rcpp::Vector<14, PreserveStorage>, Function = <lambda at double.cpp:8:21>]
sapply( const Rcpp::VectorBase<RTYPE,NA,T>& t, Function fun ){
^
2 errors generated.
make: *** [double.o] Error 1
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include  -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"    -fPIC  -O3 -c double.cpp -o double.o
Erreur dans sourceCpp(tail(args, 1), verbose = "-v" %in% args) :
  Error 1 occurred building shared library.
Exécution arrêtée
```

This is mainly `Rcpp::traits:: result_of`'s fault.

### PR DESCRIPTION
**Pull request by MattPD**
Explanation: https://github.com/RcppCore/Rcpp/issues/213#issuecomment-101023263

I think this can benefit from another pair of eyes for review and advice -- in particular, regarding the placement and naming of the constructs mentioned in the explanation (including the location of `RCPP_USE_CXX11`). Hence, feedback very much welcome! :-)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@jjallaire @kevinushey Thoughs on the PR?   

Take as is?  Generalize the macros to some wider use and some other place?

Narrowly, making `sapply` a little better should not hurt.  Rejigging the C++11 detection macros may have side effects but I guess we may need to clean up some parts at some point...

**Comment by jjallaire** [comment]
I think that as Matt said `RCPP_USE_CXX11` belongs in a more global header (not sure which to suggest, @kevinushey?) Other than that this seems like it should have few side effects (I guess changing the template definitions could break some existing code but we'd see that by just running our revdep check).

**Comment by MattPD** [comment]
Thinking out loud: perhaps renaming the aforementioned macro from `RCPP_USE_CXX11` to `RCPP_USING_CXX0X_OR_LATER` (avoids confusion with `RCPP_USING_CXX11` and consistent with the existing `_OR_LATER` naming convention) and moving it to https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/platform/compiler.h would be cleaner?

**Comment by eddelbuettel** [comment]
Yes, I like that.  

Remind me again per the discussion whether this actually does test for something new or later than previous macros?   It probably does  -- yet the macros in that [file compiler.h](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/platform/compiler.h) are all pretty old.  But that file is probably the one where we should keep these.

And if need be we could differentiate between things available with, say, g++-4.8 vs "only" g++-4.6.   

I think this very much moves in the right direction.

**Comment by MattPD** [comment]
@eddelbuettel correct: `RCPP_USING_CXX11` tests for full(er) C++11 conformance, which is not necessary for this feature (supported GCC 4.6.3 currently shipping with Rtools -- which doesn't correctly define `__cplusplus`). Proceed with PRs for this?

// Regarding differentiation -- again, thinking out loud: Some day feature-based testing may be a good refinement idea -- say, [Boost.Config](http://boost.org/libs/config)'s `BOOST_NO_CXX11_LAMBDAS`. I this context, I really like the [design](http://www.boost.org/doc/libs/master/libs/config/doc/html/boost_config/rationale.html) it uses, in particular the separation into "three orthogonal parts: the compiler, the standard library and the platform." Perhaps it may even be worth considering referencing https://github.com/boostorg/config as a Git submodule and over time switching to using [features macros](http://www.boost.org/doc/libs/master/libs/config/doc/html/boost_config/boost_macro_reference.html). It's fairly minimalistic -- and, from admittedly preliminary checks (grepping for `include`) it never includes any external dependencies (apart from `auto_link.hpp` -- depending on `version.hpp` -- which can be dropped, since it's not used for this).

**Comment by eddelbuettel** [comment]
Yes, updating the PR seems like a good idea.  Move the `#define` to the header as discussed, making the change to `sapply` smaller.   

I like the general idea of these Boost macros.  We had a related discussion here about possibly depending on BH -- but that is one truly big package.  Strategically importing small bit such as those feature macros (or the ones we need) may be a good compromise.

File: inst/include/Rcpp/sugar/functions/sapply.h [hunk 1]
```diff
@@ -22,19 +22,42 @@
 #ifndef Rcpp__sugar__sapply_h
 #define Rcpp__sugar__sapply_h
 
+#if (__cplusplus >= 201103L) || defined(__GXX_EXPERIMENTAL_CXX0X__)
+	#define RCPP_USE_CXX11 1
+#else
+	#define RCPP_USE_CXX11 0
+#endif 
+
+#if RCPP_USE_CXX11
```
Comment (kevinushey) [inline inst/include/Rcpp/sugar/functions/sapply.h]: Should this be `#ifdef` or `#if defined(RCPP_USE_CXX11)`?

**Comment by kevinushey** [comment]
The header would probably fit in here: https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/platform/compiler.h

**Comment by MattPD** [comment]
@eddelbuettel updated! Also changed the style to the `#if defined` suggested by @kevinushey, it feels more consistent.

**Comment by eddelbuettel** [comment]
That looks pretty good to me -- thanks for the update!  

Any seconds, @jjallaire or @kevinushey ?

**Comment by eddelbuettel** [comment]
@MattPD:  Do you have a full name a preferred email besides the one at `@users.noreply.github.com`?
We like to keep track of what-did-what in the `ChangeLog` which works best with an email (and also higher level in `inst/NEWS.Rd`).  I added a few things in ee8d1b22acb759723e6f9bc8163e40e82feb9844  but it is not entirely complete.

**Comment by MattPD** [comment]
@eddelbuettel: Updated, seems I might want to look into the privacy settings, thanks for the heads up! :-)

**Comment by eddelbuettel** [comment]
Thank you :) 

I have to figure out if I can catch this commit from an already-merged PR. I may just do this by hand...
